// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyALkdtYljPNhqfgmIDuBt6-XgLAl3SsFsQ',
    appId: '1:567139446673:android:b0ced6ab9d6485ebb2f430',
    messagingSenderId: '567139446673',
    projectId: 'in-my-home-ff68c',
    databaseURL: 'https://in-my-home-ff68c-default-rtdb.firebaseio.com',
    storageBucket: 'in-my-home-ff68c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCF4-CyXN4qI1ORU6UXrLbeq1iaj30xXoE',
    appId: '1:567139446673:ios:fb9bcf652341a69eb2f430',
    messagingSenderId: '567139446673',
    projectId: 'in-my-home-ff68c',
    databaseURL: 'https://in-my-home-ff68c-default-rtdb.firebaseio.com',
    storageBucket: 'in-my-home-ff68c.appspot.com',
    androidClientId: '567139446673-n9o2643j7gs9pqc1ni9ce0k5fca94tas.apps.googleusercontent.com',
    iosClientId: '567139446673-u9tq112n85cqp3rkrj0q90kqa7rtsir6.apps.googleusercontent.com',
    iosBundleId: 'com.example.app',
  );
}
